# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: time.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'time.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntime.proto\x12\x08timesync\"\r\n\x0bTimeRequest\"$\n\x0cTimeResponse\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t2M\n\x0bTimeService\x12>\n\rGetServerTime\x12\x15.timesync.TimeRequest\x1a\x16.timesync.TimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEREQUEST']._serialized_start=24
  _globals['_TIMEREQUEST']._serialized_end=37
  _globals['_TIMERESPONSE']._serialized_start=39
  _globals['_TIMERESPONSE']._serialized_end=75
  _globals['_TIMESERVICE']._serialized_start=77
  _globals['_TIMESERVICE']._serialized_end=154
# @@protoc_insertion_point(module_scope)
